### ISSUE TITLE
Driver [disqus] not supported

### ISSUE THREAD

**Issue by rogervila** [SocialiteProviders/Disqus#1]
Hello,

I have followed the steps from [the guide](http://socialiteproviders.github.io/providers/disqus/), but I get this error:
```
InvalidArgumentException in Manager.php line 90:
Driver [disqus] not supported.
```

This is my log file:
```
[2016-02-09 15:25:34] local.ERROR: exception 'InvalidArgumentException' with message 'Driver [disqus] not supported.' in /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Support/Manager.php:90
Stack trace:
#0 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('disqus')
#1 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/socialite/src/SocialiteManager.php(22): Illuminate\Support\Manager->driver('disqus')
#2 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(218): Laravel\Socialite\SocialiteManager->with('disqus')
#3 /Library/WebServer/Documents/seedomanager-tests/app/Http/Controllers/DisqusController.php(15): Illuminate\Support\Facades\Facade::__callStatic('with', Array)
#4 /Library/WebServer/Documents/seedomanager-tests/app/Http/Controllers/DisqusController.php(15): Laravel\Socialite\Facades\Socialite::with('disqus')
#5 [internal function]: App\Http\Controllers\DisqusController->login()
#6 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): call_user_func_array(Array, Array)
#7 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('login', Array)
#8 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\DisqusController), Object(Illuminate\Routing\Route), 'login')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\DisqusController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#15 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'login')
#16 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#17 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#49 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#50 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#52 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /Library/WebServer/Documents/seedomanager-tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#62 /Library/WebServer/Documents/seedomanager-tests/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#63 {main}  
```
What am I missing?
Thank you.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Reddit/issues/2#issuecomment-180399290

**Comment by AndyWendt** [comment]
Usually driver not supported means that things were not set up correctly rather than an issue with the package itself.

Please try to setup this up in a fresh install of Laravel 5.1 or 5.2 and see if you can isolate the error.

**Comment by rogervila** [comment]
Hello,

I have tried a fresh install but I get the same error. This is the code:

My `composer.json`
```js
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "socialiteproviders/disqus": "^1.1",
        "laravel/socialite": "^2.0",
        "socialiteproviders/manager": "^1.2"
    },
```

My `config/app`:
```php
//...
'providers' => [
        //...
        #Laravel\Socialite\SocialiteServiceProvider::class 
        SocialiteProviders\Manager\ServiceProvider::class
],
    //...
'aliases' => [
    //...
    'Socialite' => Laravel\Socialite\Facades\Socialite::class,
],
```


My `App\Providers\EventServiceProvider`

```php
    protected $listen = [
    
        SocialiteProviders\Manager\SocialiteWasCalled::class => [ 
            // add your listeners (aka providers) here
            'SocialiteProviders\Disqus\DisqusExtendSocialite@handle',
        ],
    ];
```

And my `app/services.php`

```php
return [
    //...
    'disqus' => [
        'client_id' => env('DISQUS_KEY'),
        'client_secret' => env('DISQUS_SECRET'),
        'redirect' => env('DISQUS_REDIRECT_URI'),  
    ], 

];
```

My controller:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DisqusController extends Controller
{

    public function index(){
    	return view('disqus');
    }

    public function login(){
    	
    	return \Socialite::with('disqus')->redirect();
    }
}
```


Am I missing something?

Thank you.

**Comment by DraperStudio** [comment]
Looks good to me. I will install the Providedr myself later today.

You don't have to require the *socialiteproviders/manager* manually, the provider will pull it in automatically.

**Comment by rogervila** [comment]
Thank you @DraperStudio 

I added it to the `composer.json` in an attempt to test what was failing, before posting the issue.

**Comment by DraperStudio** [comment]
Hm, I setup a fresh Laravel 5.1 and 5.2 last night and I had no issues with either.

Have you tried to setup a fresh instance of Laravel and only install the Disqus provider to see if it works?

**Comment by rogervila** [comment]
Thank you for trying it @DraperStudio 
This was a totally fresh install, with just the disqus provider and nothing else. I will try it in another computer with a local server, maybe is something related to my server..

Could you send me your test setup via WeTransfer or similar to my email? Maybe I am missing something in my code.

Anyway this is very strange. If it works in the other server I will notify you.

**Comment by DraperStudio** [comment]
I tried it now with Laravel 5.0, 5.1 and 5.2 and it just works when I copy your code 1:1 into fresh installs.

**Comment by AndyWendt** [comment]
Maybe the namespaces?  e.g. change `SocialiteProviders\Manager\ServiceProvider::class` to `\SocialiteProviders\Manager\ServiceProvider::class`?

**Comment by DraperStudio** [comment]
No response since a week, closed.
